name: ESP32-S3 Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4
          target: esp32s3
          path: '.'

      - name: Prepare firmware
        run: |
          mkdir -p firmware

          cp build/bootloader/bootloader.bin firmware/
          cp build/partition_table/partition-table.bin firmware/
          cp build/esp-idf-hello-world.bin firmware/
          cp build/flash_args firmware/

      - name: Merge firmware
        run: |
          python /opt/esp/idf/components/esptool_py/esptool/esptool.py \
            --chip esp32s3 \
            merge_bin \
            -o firmware/esp32s3-hello-world-merged.bin \
            --flash_mode dio \
            --flash_freq 80m \
            --flash_size detect \
            0x0 build/bootloader/bootloader.bin \
            0x8000 build/partition_table/partition-table.bin \
            0x10000 build/esp-idf-hello-world.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-firmware
          path: firmware/
