name: ESP32-S3 Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: ESP-IDF build and merge
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4
          target: esp32s3
          path: '.'
          command: |
            idf.py build
            cd build
            esptool.py --chip esp32s3 merge_bin \
              -o esp32s3-hello-world.bin \
              @flash_args

      - name: Prepare firmware
        run: |
          mkdir -p firmware
          cp build/esp32s3-hello-world.bin firmware/

          echo "Firmware:"
          ls -lh firmware/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-firmware
          path: firmware/esp32s3-hello-world.bin
